service: rest-api-java

provider:
  name: aws
  runtime: java8
  stage: ${opt:stage, 'dev'}
  region: ${self:provider.environment.REGION}
  environment:
    REGION: us-east-1
    PRODUCTS_TABLE_NAME: "${self:custom.productsTableName}"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"
    - Effect: Allow
      Action:
        - dynamodb:UpdateItem
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:DeleteItem
        - dynamodb:Query
        - dynamodb:Scan
      Resource:
        - { Fn::GetAtt: [ProductsTable, Arn] }

custom:
   productsTableName: products-table-java-${self:provider.stage}

package:
  artifact: build/libs/rest-api-java-dev-all.jar

functions:
  listProducts:
    handler: com.theagilemonkeys.labs.handlers.MainHandler
    events:
      - http: GET /products
  getProduct:
    handler: com.theagilemonkeys.labs.handlers.MainHandler
    events:
      - http: GET /product/{sku}
  createProduct:
    handler: com.theagilemonkeys.labs.handlers.MainHandler
    events:
      - http: POST /product
  updateProduct:
    handler: com.theagilemonkeys.labs.handlers.MainHandler
    events:
      - http: PATCH /product/{sku}
  deleteProduct:
    handler: com.theagilemonkeys.labs.handlers.MainHandler
    events:
      - http: DELETE /product/{sku}


resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.productsTableName}
        AttributeDefinitions:
          - AttributeName: sku
            AttributeType: S
        KeySchema:
          - AttributeName: sku
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST