service: rest-api-haskell

provider:
    name: aws
    memorySize: 1024
    runtime: provided
    stage: ${opt:stage, 'dev'}
    region: ${opt:region, 'us-east-1'}
    role: { Fn::GetAtt: [HaskellCrudRole, Arn] }

package:
    individually: true

functions:
    helloWorld:
        description: "[${self:provider.stage}] Get products - CRUD Benchmark (Haskell)"
        handler: src/Lib.handler
        package:
            artifact: "build/function.zip"
        events:
            - http:
                  path: hello
                  method: get
                  cors: true

resources:
    Resources:
        HaskellCrudRole:
            Type: AWS::IAM::Role
            Properties:
                RoleName: benchmark-haskell-role-${self:provider.stage}
                AssumeRolePolicyDocument:
                    Statement:
                        - Action: sts:AssumeRole
                          Effect: Allow
                          Principal:
                              Service: lambda.amazonaws.com
                    Version: "2012-10-17"
                Path: /
                Policies:
                    - PolicyDocument:
                          Statement:
                              - Action:
                                    - logs:CreateLogGroup
                                    - logs:CreateLogStream
                                    - logs:PutLogEvents
                                Effect: Allow
                                Resource: "*"
                          Version: "2012-10-17"
                      PolicyName: BenchMarkHaskellRoles${self:provider.stage}
